import { Header } from '@/components/layout/Header'
import { PostCard } from '@/components/blog/PostCard'
import { BookOpen, Bot, Sparkles } from 'lucide-react'
import Link from 'next/link'
import type { BlogCategory } from '@/types/database'
import { getBlogPosts } from '@/app/actions/blog'

export const metadata = {
  title: 'Blog - AI Trading Arena',
  description: 'AI-generated updates, analysis, and insights from AI Trading Arena'
}

// Fallback mock posts (used when database is empty)
const fallbackPosts = [
  {
    slug: 'welcome-to-ai-blog',
    title: 'Welcome to AI Trading Arena Blog',
    excerpt: 'All content on this blog is automatically generated by AI, providing you with the latest market analysis, crypto news, and system updates.',
    category: 'update' as BlogCategory,
    published_at: new Date().toISOString(),
    cover_image: null,
    ai_generated: true,
  },
]

const categories: { value: BlogCategory | ''; label: string; icon: string }[] = [
  { value: '', label: 'All Posts', icon: '📚' },
  { value: 'update', label: 'Updates', icon: '📢' },
  { value: 'analysis', label: 'Analysis', icon: '📊' },
  { value: 'tech', label: 'Tech', icon: '🔧' },
  { value: 'crypto', label: 'Crypto', icon: '₿' },
]

export default async function BlogPage({
  searchParams,
}: {
  searchParams: Promise<{ category?: string }>
}) {
  const params = await searchParams
  const selectedCategory = (params.category || '') as BlogCategory | ''

  // Fetch posts from Supabase
  const { posts: dbPosts } = await getBlogPosts(
    selectedCategory ? { category: selectedCategory as BlogCategory } : undefined
  )

  // Use database posts or fallback
  const posts = dbPosts.length > 0 ? dbPosts : fallbackPosts

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950">
      <Header />

      <main className="container mx-auto px-4 py-8">
        {/* Page Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold mb-2 flex items-center justify-center gap-2">
            <BookOpen className="w-8 h-8 text-green-500" />
            Blog
          </h1>
          <p className="text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
            AI-powered updates, market analysis, and insights - automatically generated twice daily
          </p>

          {/* AI Badge */}
          <div className="mt-4 inline-flex items-center gap-2 px-3 py-1.5 bg-purple-100 dark:bg-purple-900/30 rounded-full text-sm text-purple-700 dark:text-purple-300">
            <Bot className="w-4 h-4" />
            <span>100% AI Generated Content</span>
            <Sparkles className="w-4 h-4" />
          </div>
        </div>

        {/* Category Filter */}
        <div className="flex items-center justify-center gap-2 mb-8 flex-wrap">
          {categories.map((cat) => (
            <Link
              key={cat.value}
              href={cat.value ? `/blog?category=${cat.value}` : '/blog'}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors flex items-center gap-1.5 ${
                selectedCategory === cat.value
                  ? 'bg-green-600 text-white'
                  : 'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 border dark:border-gray-700'
              }`}
            >
              <span>{cat.icon}</span>
              {cat.label}
            </Link>
          ))}
        </div>

        {/* Posts Grid */}
        {posts.length > 0 ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {posts.map((post) => (
              <PostCard
                key={post.slug}
                slug={post.slug}
                title={post.title}
                excerpt={post.excerpt}
                category={post.category}
                publishedAt={post.published_at}
                coverImage={post.cover_image}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-12 text-gray-500">
            <BookOpen className="w-12 h-12 mx-auto mb-4 opacity-50" />
            <p>No posts found in this category</p>
            <Link href="/blog" className="text-green-600 hover:underline text-sm mt-2 inline-block">
              View all posts
            </Link>
          </div>
        )}

        {/* Auto-Generation Info */}
        <div className="max-w-2xl mx-auto mt-16">
          <div className="bg-gradient-to-r from-purple-600 to-indigo-600 rounded-xl p-8 text-white text-center">
            <div className="flex items-center justify-center gap-2 mb-3">
              <Bot className="w-6 h-6" />
              <h2 className="text-xl font-bold">Fully Automated Blog</h2>
            </div>
            <p className="text-purple-100 mb-4">
              This blog is powered by AI. New posts are automatically generated twice daily at 9AM and 9PM,
              featuring market analysis, crypto news, tech updates, and system announcements.
            </p>
            <div className="flex items-center justify-center gap-6 text-sm">
              <div className="flex items-center gap-1">
                <span className="text-purple-200">Content:</span>
                <span className="font-semibold">Claude Opus</span>
              </div>
              <div className="flex items-center gap-1">
                <span className="text-purple-200">Images:</span>
                <span className="font-semibold">Gemini Imagen</span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
